version: '3.8'

services: 
  app:
    build: /backend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./tmp:/tmp
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    env_file:
      - dev.env
    ports:
      - "5432:5432"