version: '3.8'

services: 
  backend:
    build: /backend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./tmp:/tmp
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5435:5432"